<section class="content">
<div class="row">
  <div class="col-md-2 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-aqua"><i class="fa fa-bank"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Colegios</span>
        <span class="info-box-number"><?php echo $col ?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->
  <div class="col-md-2 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-green"><i class="fa fa-male"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Estudiantes</span>
        <span class="info-box-number"><?php echo $alm?></span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
  <!-- /.col -->

        <!-- fix for small devices only -->
  <div class="clearfix visible-sm-block"></div>
  <?php foreach($estados as $estado){?>
    <div class="col-md-2 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon <?php echo $estado->color?>"><i class="<?php echo $estado->icono?>"></i></span>

        <div class="info-box-content">
          <span class="info-box-text"><?php echo $estado->nombre?></span>
          <span class="info-box-number"><?php echo $estado->getTotal()?></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
  <?php }?>
        <!-- /.col -->
</div>
<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Estudiantes recien agregados</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <ul class="products-list product-list-in-box">
        <?php foreach($alumnos as $alumno){?>
        <li class="item">
          <div class="product-img">
            <img src="/img/<?php echo $alumno->sexo?>.png" alt="Alumno">
          </div>
          <div class="product-info">
            <a href="/apps/buscador/alumno/<?php echo $alumno->id?>" class="product-title"><?php echo $alumno->nombres?> <?php echo $alumno->appelido_paterno?> <?php echo $alumno->apellido_materno?>,  DNI: <?php echo $alumno->dni?>, Codigo: <?php echo $alumno->codigo_estudiante?></a>
            <span class="product-description">
              <?php foreach ($alumno->getDeudas() as $deuda) {
                echo ' <span class="with-border label '.$deuda->getEstados()->color.'">'.$deuda->mes.'-'.$deuda->anio.', '.$deuda->descripcion.' '.$deuda->getColegios()->nombre.'</span>';
                //echo '<pre>';
               // print_r($deuda);
                //echo '</pre>';
              }?>
            </span>
          </div>
        </li>
        <?php }?>
        
        <!-- /.item -->
      </ul>
    </div>
            <!-- /.box-body -->
    <div class="box-footer text-center">
      <div class="btn-group">
        <a href="/apps/buscador" class="uppercase btn btn-flat ">Buscar</a>
      <a href="/apps/micolegio" class="uppercase btn btn-flat">Mi colegio</a>
      </div>
      
    </div>
    <!-- /.box-footer -->
  </div>
</section>