<div class="box-header with-border">
    <h1 class="box-title">Crear Empresa</h1>
</div>
<div class="box-body">    
    <?php View::content() ?>
    <?php echo Form::open(NULL, 'post', 'role="form" class="form-horizontal"') ?>
    <?php echo Form::hidden('aclempresas.id') ?>
    <?php echo Form::hidden('colegios.id');?>
    <?php echo Form::hidden('colegios.estado',NULL,1) ?>


    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Ugel: ','colegios.ugeles_id','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::dbSelect('colegios.ugeles_id','nombre',NULL,'Seleccione una ugel','class="form-control" required') ?></div>            
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Nombre de la Empresa: ','colegios.nombre','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('colegios.nombre','class="form-control" required') ?></div>            
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Razon Social:  ','aclempresas.razonsocial','class="col-sm-3 control-label"');?>
                <div class="col-sm-9">
                    <?php echo Form::text('aclempresas.razonsocial','class="form-control" required') ?>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Direccion: ','colegios.direccion','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('colegios.direccion','class="form-control" required') ?></div>      
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Ruc: ','aclempresas.ruc','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('aclempresas.ruc','class="form-control" required') ?></div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Codigo local: ','colegios.codigo_local','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('colegios.codigo_local','class="form-control" required') ?></div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Codigo Modular: ','colegios.codigo_modular','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('colegios.codigo_modular','class="form-control" required') ?></div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Telefono Fijo: ','aclempresas.telefonos','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('aclempresas.telefonos','class="form-control"') ?></div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Fax: ','aclempresas.telefonos1','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('aclempresas.telefonos1','class="form-control"') ?></div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <?php echo Form::label('Celular/Movil: ','aclempresas.telefonos1','class="col-sm-3 control-label"');?>
                <div class="col-sm-9"><?php echo Form::text('aclempresas.telefonos2','class="form-control"') ?></div>
            </div> 
        </div>
    </div>   
</div>
<div class="box-footer">
    <div class="form-actions pull-right">
        <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
</div>
<?php echo Form::close() ?>