<section class="content">

      <div class="row">
        <div class="col-md-3">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="/img/colesperu.png" alt="User profile picture">

              <h3 class="profile-username text-center"><?php echo $colegio->nombre?></h3>

              <p class="text-muted text-center"><?php echo $colegio->getAclempresas()->razonsocial?></p>

              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Total de estudiantes</b> <a class="pull-right"><?php echo $colegio->total_alumnos?></a>
                </li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

          <!-- About Me Box -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">informacion</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <strong><i class="fa fa-barcode margin-r-5"></i> Codigo modular</strong>

              <p class="text-muted">
               <?php echo $colegio->codigo_modular?>
              </p>

              <hr>
              <strong><i class="fa fa-bookmark margin-r-5"></i> Codigo local</strong>

              <p class="text-muted">
               <?php echo $colegio->codigo_local?>
              </p>

              <hr>
              <strong><i class="fa fa-book margin-r-5"></i> Ruc</strong>

              <p class="text-muted">
                <?php echo $colegio->getAclempresas()->ruc?>
              </p>

              <hr>

              <strong><i class="fa fa-map-marker margin-r-5"></i> Direccion</strong>

              <p class="text-muted"><?php echo $colegio->direccion?></p>

              <hr>

              <!-- <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>

              <p>
                <span class="label label-danger">UI Design</span>
                <span class="label label-success">Coding</span>
                <span class="label label-info">Javascript</span>
                <span class="label label-warning">PHP</span>
                <span class="label label-primary">Node.js</span>
              </p>

              <hr>

              <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p> -->
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#activity" data-toggle="tab" aria-expanded="true">Actividades</a></li>
              <li><a href="/apps/micolegio/alumnos">Estudiantes</a></li>
              <li class=""><a href="/apps/micolegio/editar">Configuracion</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="activity">
                <!-- Post -->
                <?php foreach($deudas as $deuda){?>
                <div class="post">
                  <div class="user-block">
                    <img class="img-circle img-bordered-sm" src="/img/<?php echo $deuda->sexo?>.png" alt="user image">
                        <span class="username">
                          <a href="#"><?php echo $deuda->nombres?> <?php echo $deuda->paterno?> <?php echo $deuda->materno?></a>
                          <a href="#" class="pull-right btn-box-tool">
                            <i class="fa"></i></a>
                        </span>
                    <span class="description"><?php echo $deuda->creacion?></span>
                  </div>
                  <!-- /.user-block -->
                  <p>
                  <?php echo $deuda->descripcion?>
                  </p>
                </div>
              <?php }?>
                <!-- /.post -->
              </div>

            </div>
            <!-- /.tab-content -->
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
</section>